services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: demoDB
    ports:
      - "3306:3306"

  spring-app:
    image: vanduy41/myapp
    container_name: spring-container
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/demoDB
    depends_on:
      - mysql